spring:
  qq:
    username: 3970363733@qq.com
    password: wxjyokxvooipceia
    admin:
      - 2315212099@qq.com
      - l3377580541@qq.com
  application:
    name: esshs
  datasource:
    url: jdbc:mysql://192.168.137.164:23307/esshs?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 192.168.137.164
      password: 123
      port: 6379
      lettuce:
        pool:
          # ????????????????????
          max-active: 8
          # ???????????????????????
          max-wait: 10000ms
          # ???????????
          max-idle: 8
          # ???????????
          min-idle: 0
        # ??????????
        shutdown-timeout: 0
server:
  port: 8080
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto
knife4j:
  enable: true    #开启knife4j,无需添加@EnableKnife4j注解
  setting:
    language: zh_cn   #中文
    swagger-model-name: 实体类列表   #重命名SwaggerModel名称,默认